import React from 'react';
import type { MigrationAssuranceReport } from '../types/migration';
import { CodePanel } from '../components/CodePanel';

interface TranslationViewProps {
  report: MigrationAssuranceReport;
}

export const TranslationView: React.FC<TranslationViewProps> = ({ report }) => {
  const summary = report.translation_summary;

  return (
    <div>
      {/* Header & Status Labels */}
      <div className="card-panel">
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: '16px' }}>
          <div>
            <h3>AI-TRANSLATED TARGET CANDIDATE</h3>
            <p style={{ fontSize: '13px', color: '#64748B', marginTop: '2px' }}>
              Generated by dialect-aware AI structural model ({summary?.provider || 'mock'} / {summary?.model || 'mock-model'})
            </p>
          </div>

          <div style={{ display: 'flex', gap: '12px' }}>
            <div style={{ backgroundColor: '#F0FDF4', color: '#166534', padding: '6px 12px', borderRadius: '6px', fontSize: '12px', fontWeight: 600, border: '1px solid #86EFAC' }}>
              Candidate: {summary?.candidate_validation_status || 'VALID_SYNTAX'}
            </div>
            <div style={{ backgroundColor: '#FFFBEB', color: '#92400E', padding: '6px 12px', borderRadius: '6px', fontSize: '12px', fontWeight: 600, border: '1px solid #FDE68A' }}>
              Semantic Status: NOT_EVALUATED
            </div>
          </div>
        </div>
      </div>

      {/* Code Comparison Layout */}
      <div className="card-panel">
        <h3 style={{ marginBottom: '16px' }}>SQL CODE COMPARISON</h3>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(360px, 1fr))', gap: '20px' }}>
          <CodePanel
            title={`SOURCE SQL (${summary?.source_dialect.toUpperCase() || 'TERADATA'})`}
            code={
`SELECT
    c.customer_id,
    c.customer_segment,
    SUM(t.amount) AS total_amount,
    CASE
        WHEN t.amount > 500
        THEN 'HIGH_RISK'
        ELSE 'NORMAL'
    END AS risk_class
FROM transactions AS t
INNER JOIN customers AS c
    ON t.customer_id = c.customer_id
WHERE t.status = 'COMPLETED'
GROUP BY c.customer_id, c.customer_segment, t.amount;`
            }
          />

          <CodePanel
            title={`TARGET SQL CANDIDATE (${summary?.target_dialect.toUpperCase() || 'BIGQUERY'})`}
            code={
`SELECT
  c.customer_id,
  c.customer_segment,
  SUM(t.amount) AS total_amount,
  CASE WHEN t.amount >= 500.00 THEN 'HIGH_RISK' ELSE 'NORMAL' END AS risk_class
FROM transactions t
JOIN customers c ON t.customer_id = c.customer_id
WHERE t.status = 'COMPLETED'
GROUP BY c.customer_id, c.customer_segment, t.amount;`
            }
          />
        </div>
      </div>

      {/* Structured Logic Breakdown */}
      <div className="card-panel">
        <h3 style={{ marginBottom: '12px' }}>STRUCTURED LOGIC BREAKDOWN</h3>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '16px' }}>
          <div style={{ backgroundColor: '#F8FAFC', padding: '14px', borderRadius: '6px', border: '1px solid #E2E8F0' }}>
            <div style={{ fontSize: '12px', fontWeight: 600, color: '#64748B' }}>Target Tables</div>
            <div style={{ fontSize: '14px', fontWeight: 600, color: '#0F172A', marginTop: '4px' }}>transactions, customers</div>
          </div>
          <div style={{ backgroundColor: '#F8FAFC', padding: '14px', borderRadius: '6px', border: '1px solid #E2E8F0' }}>
            <div style={{ fontSize: '12px', fontWeight: 600, color: '#64748B' }}>Join Conditions</div>
            <div style={{ fontSize: '14px', fontWeight: 600, color: '#0F172A', marginTop: '4px' }}>t.customer_id = c.customer_id</div>
          </div>
          <div style={{ backgroundColor: '#F8FAFC', padding: '14px', borderRadius: '6px', border: '1px solid #E2E8F0' }}>
            <div style={{ fontSize: '12px', fontWeight: 600, color: '#64748B' }}>Aggregations</div>
            <div style={{ fontSize: '14px', fontWeight: 600, color: '#0F172A', marginTop: '4px' }}>SUM(t.amount)</div>
          </div>
          <div style={{ backgroundColor: '#F8FAFC', padding: '14px', borderRadius: '6px', border: '1px solid #E2E8F0' }}>
            <div style={{ fontSize: '12px', fontWeight: 600, color: '#64748B' }}>CASE Expression</div>
            <div style={{ fontSize: '14px', fontWeight: 600, color: '#2563EB', marginTop: '4px' }}>t.amount &gt;= 500.00</div>
          </div>
        </div>
      </div>
    </div>
  );
};
